void SaveTFTid();
void TargetTempSet();
void RedLED();
void GreenLED();
void BlueLED();
void WhiteLED();
void BrownLED();
void OrangeLED();
void YellowLED();
void OffLED();
void ReadVolts();
void ReadTempReturn();
void ReadTempExit();
void ReadTempTop();
void ReadTempBat();
void ReadTempReturnDigital();
void ReadTempBatDigital();
void DigitalTempInit();
void DigitalTempsLog();
void EpochStart();
void EpochTick();
void EpochSet();
void FindFlashOffset();
void LogFlashStatus1();
void LogFlashStatus5();
void LogFlashDebug();
void DumpAllFlash();
void WriteSPIBuf();
void EraseAllFlash();
void CalcFans();
void CalcMainFain();
void incrementAverages();
void calculateAverages1();
void calculateAverages5();
void IceFanInit();
unsigned int IceFanReadRPM();
void CalcIceFanRPM();
void PrintNowData();
void PrintPositionStatus();
void RePrintPositionData();
void PrintPositionData();
void PrintStatus();
void PrintSPIBuf();
void PrintSPIBuf2();
void PrintTargets();
void PrintAverages1();
void PrintAverages5();
void PrintNowCRC();
void PrintFlashCRC();
void RePrintFlashCRC();
void PrintVCCTemp();
void ReadVCCTemp();
void DecVCCTemp();
void IncVCCTemp();
void PrintVCCTemp2();
void ReadVCCTemp2();
void DecVCCTemp2();
void IncVCCTemp2();
byte SumDigits(unsigned long);
byte CRCDigits(unsigned long);
void PrintHelpMenu(int);
void SPIFlashInit();
byte CheckOffsetUsed(unsigned long);
void ReadSPIBuf(unsigned long);
void JumpDown(unsigned long);
void JumpUp(unsigned long);
unsigned int ADC2Temp(int);


